### PR TITLE
PXC-3444: Node crashes for duplicated statements replicated as TOI

### PR DESCRIPTION
**Pull request by nitendra-bhosle**
https://jira.percona.com/browse/PXC-3444

Analysis :
Node crashes while DML is executed in TOI mode,
and getting rollback.
This behavior is specific for PXC only where DML can be replicated in TOI mode. 
This is used by pt-table-checksum tool which injects 99997 version 
into the insert.. select query.

Fix: 
Handled m_toi transaction state on rollback,
by aborting transaction while DML is executed in TOI mode.

### CODE REVIEW

**Comment by nitendra-bhosle** [comment]
PXC Jenkins :https://pxc.cd.percona.com/view/PXC%208.0/job/pxc-8.0-param/319/

**Comment by dutow** [comment]
Please also include a test case for this in the PXC part of the PR / jenkins test.

And please also update the JIRA ticket / commit message to reflect the actual issue: while Kamil originally found it by executing the same insert twice, the actual issue isn't that we have duplicated inserts, it's the fact that the second insert fails because of a duplicate primary key.

Simply executing the same insert twice works if it isn't rolled back (e.g. if you remove the primary key from t2).

**Review by kamil-holubicki — CHANGES_REQUESTED** [review]
Hi, the change looks fine, but please write a detailed explanation in the commit message (and maybe something inside the code as well) why we need it.
This behavior is specific for PXC only where DML can be replicated in TOI mode. This is used by pt-table-checksum tool which injects 99997 version into the insert.. select query

**Comment by kamil-holubicki** [comment]
Hi @nitendra-bhosle , If I'm not mistaken only the comment visible in GitHub was adjusted. Commit message is still missing the information "why we need it".
Please updated the commit message while squashing commits before the merge.

**Review by kamil-holubicki — APPROVED** [review]
lgtm. Please update commit message and squash commits before merging.

**Pull request merged**
